# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "AFLplusplus-4.21.0-aA1y4dZxAAAhqDy_JoRw3zwNSg8MenEGP7uJI_xNcYuV";
    path = fetchgit {
      url = "https://github.com/allyourcodebase/AFLplusplus";
      rev = "7e65eb4262688a120bf830d145060aac0e5db920";
      hash = "sha256-f5Egmkg2tEOV5jfcNj9KTU0IWOAC/hGdypmC+IG88Q0=";
    };
  }
  {
    name = "N-V-__8AAKE4uAAJZgEcPdaXnWqoj-IwYf3G2h9YSm-x92gg";
    path = fetchzip {
      url = "https://github.com/AFLplusplus/AFLplusplus/archive/v4.21c.tar.gz";
      hash = "sha256-DKwPRxSO+JEJYWLldnfrAYqzwqukNzrbo4R5FzJqzzg=";
    };
  }
  {
    name = "afl_kit-0.1.0-NdJ3ch8eAABQkd1wk2W-JDCvvX5Jmnu3uJulS3lPepG7";
    path = fetchgit {
      url = "https://github.com/kristoff-it/zig-afl-kit";
      rev = "395c39d5b33d999f6871a90bd731ec112d3995ca";
      hash = "sha256-+hfv+gAQr53rT2O1n+8BO/HIYVJx1KWplKTMGxVMLH8=";
    };
  }
  {
    name = "elfy-0.1.0-BML8Mk0hAQDYd5NXyKDuD3QLDPRLMtlk8ThwMpKQSjSq";
    path = fetchgit {
      url = "https://github.com/leifhelm/elfy.zig.git";
      rev = "f255240ef2c8ad033fd67c5b4f53767ae83a219b";
      hash = "sha256-UHMO07ScfbYxCW3XdGc/ekW7+DTd6HBwLvz6Q5fhBns=";
    };
  }
  {
    name = "ucl-0.0.0-vwd2_30VAQAVhBoWo92cc_WDzvT1Cu2tV59PacXvFC3G";
    path = fetchgit {
      url = "https://github.com/leifhelm/ucl-zig.git";
      rev = "39ea32f4fb3578e9dc48393061eeead4f3fbd5be";
      hash = "sha256-pxP7hFemCPfRfwmh71ex0q3S++JirYoGQLvGmcnGmnk=";
    };
  }
]
